services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/larahh

  php:
    build:
      context: ./
      dockerfile: php.Dockerfile
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}

    volumes:
      - ./:/var/www/larahh

  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - docker-compose/mysql/mysql.env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
